# Generated by Django 3.2.5 on 2021-07-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_number', models.IntegerField(verbose_name='شماره دوره ')),
                ('prd_fasl', models.IntegerField(verbose_name='فصل دوره')),
                ('prd_startdate', models.IntegerField(verbose_name='تاریخ شروع دوره ')),
                ('prd_finishdate', models.IntegerField(verbose_name='تاریخ پایان دوره')),
                ('prd_modat', models.IntegerField(verbose_name='مدت دوره')),
                ('prd_tedadjoje', models.IntegerField(verbose_name='تعداد جوجه ')),
            ],
        ),
    ]
