# Generated by Django 3.2.5 on 2021-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyperformanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlp_date', models.IntegerField(verbose_name=' تاریح  روز')),
                ('dlp_sen', models.IntegerField(verbose_name='سن گله ')),
                ('dlp_talafat', models.IntegerField(verbose_name='تعداد تلفات ')),
                ('dlp_hazfi', models.IntegerField(verbose_name='تعداد حذفی ')),
                ('dlp_talafatkol', models.IntegerField(verbose_name=' تلفات کل ')),
                ('dlp_danmasrafi', models.IntegerField(verbose_name='مقدار دان مصرفی ')),
                ('dlp_dankol', models.IntegerField(verbose_name='دان مصرفی کل ')),
                ('dlp_saranedan', models.IntegerField(verbose_name='سرانه مصرفی دان ')),
                ('dlp_vazn', models.IntegerField(verbose_name='میانگین وزن ')),
                ('dlp_afzayeshvaznroozane', models.IntegerField(verbose_name='افزایش وزن روزانه ')),
                ('dlp_dama', models.IntegerField(verbose_name='میانگین دما ')),
                ('dlp_abmasrafi', models.IntegerField(verbose_name='مقدار اب مصرفی ')),
                ('dlp_etefaghat', models.IntegerField(verbose_name='اتفاقات مهم ')),
                ('dlp_daroo', models.IntegerField(verbose_name='دارو مصرفی ')),
                ('dlp_vaksan', models.IntegerField(verbose_name='واکسن مصرفی  ')),
                ('dlp_tozih', models.IntegerField(verbose_name='توضیحات  ')),
            ],
        ),
        migrations.CreateModel(
            name='JojeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joj_sen', models.IntegerField(verbose_name='شماره دوره ')),
                ('joj_talafat', models.IntegerField(verbose_name='شماره دوره ')),
                ('joj_hazfi', models.IntegerField(verbose_name='شماره دوره ')),
                ('joj_jamekol', models.IntegerField(verbose_name='شماره دوره ')),
                ('joj_vazn', models.IntegerField(verbose_name='شماره دوره ')),
                ('joj_tozihat', models.IntegerField(verbose_name='شماره دوره ')),
                ('joj_nehad', models.IntegerField(verbose_name='شماره دوره ')),
                ('joj_namemadar', models.IntegerField(verbose_name='شماره دوره ')),
                ('joj_senmadar', models.IntegerField(verbose_name='شماره دوره ')),
            ],
        ),
    ]
