# Generated by Django 3.2.5 on 2021-07-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0002_dailyperformancemodel_jojemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyperformancemodel',
            options={'verbose_name': 'عملکرد روزانه  ', 'verbose_name_plural': 'عملکرد روزانه '},
        ),
        migrations.AlterModelOptions(
            name='jojemodel',
            options={'verbose_name': 'ثبت اطلاعات جوجه  ', 'verbose_name_plural': 'ثبت اطلاعات جوجه '},
        ),
        migrations.AlterModelOptions(
            name='periodmodel',
            options={'verbose_name': 'اطلاعات دوره  ', 'verbose_name_plural': 'اطلاعات دوره '},
        ),
    ]
