# Generated by Django 3.2.5 on 2021-07-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_onvan', models.CharField(max_length=30, verbose_name='شرح هزینه')),
                ('ct_date', models.DateField(verbose_name='تاریخ ')),
                ('ct_mablagh', models.IntegerField(verbose_name='مبلغ هزینه')),
                ('ct_desc', models.CharField(max_length=300, verbose_name='توضیحات هزینه')),
            ],
        ),
    ]
