# Generated by Django 3.2.5 on 2021-07-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fainance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sln_name', models.CharField(max_length=30, verbose_name='نام سالن')),
                ('sln_tedad', models.IntegerField(verbose_name='تعداد سالن')),
                ('sln_zarfiat', models.IntegerField(verbose_name='ظرفیت سالن')),
            ],
        ),
        migrations.AlterModelOptions(
            name='costmodel',
            options={'verbose_name': 'هزینه ها ', 'verbose_name_plural': 'هزینه ها'},
        ),
        migrations.CreateModel(
            name='FarmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm_name', models.CharField(max_length=30, verbose_name='نام فارم')),
                ('frm_zarfiat', models.IntegerField(verbose_name='ظرفیت فارم')),
                ('frm_tedad_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fainance.salonmodel')),
            ],
        ),
    ]
