# Generated by Django 3.2.5 on 2021-07-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fainance', '0002_auto_20210724_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonmodel',
            name='sln_tedad',
        ),
        migrations.AlterField(
            model_name='farmmodel',
            name='frm_tedad_salon',
            field=models.IntegerField(verbose_name='تعداد سالن'),
        ),
    ]
