# Generated by Django 3.2.5 on 2021-07-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fainance', '0003_auto_20210724_0546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmModel',
        ),
        migrations.DeleteModel(
            name='SalonModel',
        ),
    ]
