# Generated by Django 3.2.5 on 2021-07-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm_name', models.CharField(max_length=30, verbose_name='نام فارم')),
                ('frm_zarfiat', models.IntegerField(verbose_name='ظرفیت فارم')),
                ('frm_tedad_salon', models.IntegerField(verbose_name='تعداد سالن')),
            ],
        ),
        migrations.CreateModel(
            name='SalonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sln_name', models.CharField(max_length=30, verbose_name='نام سالن')),
                ('sln_zarfiat', models.IntegerField(verbose_name='ظرفیت سالن')),
            ],
        ),
    ]
