# Generated by Django 3.2.5 on 2021-07-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmmodel',
            options={'verbose_name': 'مدیریت فارم ', 'verbose_name_plural': 'مدیریت فارم '},
        ),
        migrations.AlterModelOptions(
            name='salonmodel',
            options={'verbose_name': 'مدیریت سالن  ', 'verbose_name_plural': 'مدیریت سالن '},
        ),
        migrations.AddField(
            model_name='salonmodel',
            name='sln_frm_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.farmmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonmodel',
            name='sln_tedad',
            field=models.IntegerField(default=3, verbose_name='تعداد سالن'),
            preserve_default=False,
        ),
    ]
